behaviors:
    KillerBehaviour:
        trainer_type: ppo
        hyperparameters:
            batch_size: 32000
            buffer_size: 128000
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 8
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 6666666
        time_horizon: 64
        summary_freq: 60000  
    CamperBehaviour:
        trainer_type: poca
        hyperparameters:
            batch_size: 32000
            buffer_size: 128000
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 8
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 384
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 64
        summary_freq: 60000
env_settings:
    env_path: null
    env_args: null
    base_port: 5005
    num_envs: 1
    seed: -1
engine_settings:
    width: 84
    height: 84
    quality_level: 5
    time_scale: 50
    target_frame_rate: -1
    capture_frame_rate: 60
    no_graphics: true
environment_parameters: null
checkpoint_settings:
    run_id: run_results
    initialize_from: null
    load_model: false
    resume: false
    force: false
    train_model: true
    inference: false
    results_dir: results
torch_settings:
    device: cuda
debug: false
