behaviors:
    KillerBehaviour:
        trainer_type: ppo
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0001
            beta: 0.001
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 8
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 64
            num_layers: 2
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 6666666
        time_horizon: 1000
        summary_freq: 20000
    CamperBehaviour:
        trainer_type: poca
        hyperparameters:
            batch_size: 5120
            buffer_size: 51200
            learning_rate: 0.00001
            beta: 0.0001
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 8
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 5120
        summary_freq: 60000
env_settings:
    env_path: null
    env_args: null
    base_port: 5005
    num_envs: 1
    seed: -1
engine_settings:
    width: 84
    height: 84
    quality_level: 5
    time_scale: 30
    target_frame_rate: -1
    capture_frame_rate: 60
    no_graphics: false
environment_parameters: null
checkpoint_settings:
    run_id: run_results
    initialize_from: null
    load_model: false
    resume: false
    force: false
    train_model: true
    inference: false
    results_dir: results
torch_settings:
    device: cuda
debug: false
