behaviors:
    CamperBehaviour:
        trainer_type: poca
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 5
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.01
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 1000
        summary_freq: 60000
        self_play:
          save_steps: 90000
          team_change: 450000
          swap_steps: 90000
          window: 10
          play_against_latest_model_ratio: 0.5
          initial_elo: 1200.0
    MosquitoBehaviour:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 5
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 512
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.01
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 1000
        summary_freq: 60000
        self_play:
          save_steps: 30000
          team_change: 150000
          swap_steps: 10000
          window: 10
          play_against_latest_model_ratio: 0.5
          initial_elo: 1200.0
environment_parameters:
  training_stage_index:
    curriculum:
      - name: Stage0
        completion_criteria:
          measure: reward
          behavior: CamperBehaviour
          signal_smoothing: true
          min_lesson_length: 200
          threshold: 0.5
        value: 0
      - name: Stage1
        completion_criteria:
          measure: reward
          behavior: CamperBehaviour
          signal_smoothing: true
          min_lesson_length: 200
          threshold: -0.25
        value: 1
      - name: Stage2
        completion_criteria:
          measure: reward
          behavior: CamperBehaviour
          signal_smoothing: true
          min_lesson_length: 200
          threshold: -0.2
        value: 2
      - name: Stage3
        completion_criteria:
          measure: reward
          behavior: CamperBehaviour
          signal_smoothing: true
          min_lesson_length: 200
          threshold: -2
        value: 3
      - name: Stage4
        value: 4
