behaviors:
    MosquitoBehaviour:
        trainer_type: ppo
        hyperparameters:
            batch_size: 1024
            buffer_size: 10240
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 5
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 1
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 1000
        summary_freq: 60000
    CamperBehaviour:
        trainer_type: poca
        hyperparameters:
            batch_size: 2048
            buffer_size: 20480
            learning_rate: 0.0003
            beta: 0.005
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 5
            learning_rate_schedule: constant
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 3
            vis_encode_type: simple
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
        keep_checkpoints: 5
        max_steps: 20000000
        time_horizon: 1000
        summary_freq: 60000
